# Generated by Django 5.0.7 on 2024-08-12 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bannar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='bannar_image/')),
                ('product_name', models.CharField(blank=True, max_length=400, null=True)),
                ('price', models.CharField(max_length=14)),
                ('discount_price', models.CharField(max_length=14)),
            ],
            options={
                'verbose_name_plural': 'Bannars',
            },
        ),
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name_plural': 'Contact Informations'},
        ),
    ]
