# Generated by Django 5.0.7 on 2024-08-12 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_bannar_alter_contactinfo_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bannar',
            new_name='Banner',
        ),
    ]
